### DISCUSSION TITLE
Running with docker compose

### DISCUSSION THREAD

**Discussion by PaulRudin** [v6d-io/v6d#1325] [Q&A] [answered]
I'm experimenting with vineyard. I made an image from the following Dockerfile:
```
FROM python:3.11-slim

RUN pip install vineyard

CMD python -m vineyard --socket /var/run/vineyard.sock
```
I create a file:
```
touch /tmp/vineyard.sock
```
And my docker-compose.yml has a vineyard service:
```
vineyard:
    ...
    volumes:
      - type: bind
        source: /tmp/vineyard.sock
        target: /var/run/vineyard.sock
```
But in the logs I see:
```
20230420 12:20:38.759117     7 vineyardd.cc:107] Hello vineyard v0.14.0!

Unhandled exception:
   std::exception:what(): bind: Address already in use
```
How can I get this to work?
