### ISSUE TITLE
Add a general field to the Vineyardd CRD for supporting the most APIs of Kubernetes Deployment 

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1439]
Describe your problem
---------------------

At present, we have the `Vineyardd` CRD to deploy a Kubernetes Deployment, but it only contains the parts of Kubernetes Deployment APIs refer to [vineyardd template file](https://github.com/v6d-io/v6d/blob/main/k8s/pkg/templates/vineyardd/deployment.yaml), it's better to add a field to the Vineyardd CRD which allows users to input their custom APIs rather than the fields of CRD.

Some examples:

```yaml
apiVersion: k8s.v6d.io/v1alpha1
kind: Vineyardd
metadata:
  name: vineyardd-sample
spec:
  replicas: 3
  vineyard:
    image: vineyardcloudnative/vineyardd:latest
    imagePullPolicy: IfNotPresent
  # the extraFields are only merged into the vineyard deployment
  extraFields:
    spec:
      template:
        spec:
          tolerations:
          - effect: NoSchedule
            key: disktype
            value: ssd
```

Additional context
------------------

- Users want to add taints and tolerations to the Vineyard Deployment. #1355  
- You could get some inspiration from the [kubectl patch](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/)
