### ISSUE TITLE
The workload can't be scheduled on the vineyard cluster deployed on different namespace

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1501]
Describe your problem
---------------------

1. Deploy the vineyard deployment as follows.

```bash
$ vineyardctl deploy vineyard-deployment --replicas=1 --create-namespace
```

2. Assume we have the following workload yaml.

```yaml
$ cat workload.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-client
  namespace: vineyard-job
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python:3.10
        command: ["python", "-c", "import time; time.sleep(100000)"]
```

3. Then schedule the workload to the vineyard deployment as follows.

```bash
$ kubectl create ns vineyard-job && vineyardctl schedule workload -f workload.yaml | kubectl apply -f -
```

4. The workload pod will always keep pending as no nodes are available.
