### ISSUE TITLE
vineyardctl can't list all metadatas of vineyard deployment

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1525]
Describe your problem
---------------------

When we use the `vineyardctl ls metadatas` to get the metadata of a vineyard deployment, assume the deployment has three replicas, and each vineyard pod is deployed on a different node. The current design can't list all metadatas of all vineyard pods as it can only connect one vineyard pod and get the relevant metadatas. The issue is to improve the `vineyardctl ls metadatas` command so that it can list all metadatas.

**Comment by sighingnow** [comment]
Cannot reproduce.

Please make sure your two vineyardd instances are connected to the same etcd server.

**Comment by dashanji** [comment]
Reproduce steps:

1. Create a kubernetes cluser with 3 worker nodes.
2. Use the command `vineyardctl deploy vineyard-deployment --create-namespace` to deploy the vineyard cluster.
3. Apply the yamls as follows.
```yaml
$ cat <<EOF | kubectl apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: v6d-workflow-demo-job1
  namespace: vineyard-job
spec:
  parallelism: 2
  template:
    metadata:
      annotations:
        workloadSelector: app=v6d-workflow-demo-job1
      labels:
        app: v6d-workflow-demo-job1
        # this label represents the vineyardd's name that need to be used
        scheduling.k8s.v6d.io/vineyardd-namespace: vineyard-system
        scheduling.k8s.v6d.io/replicas: "2"
        scheduling.k8s.v6d.io/vineyardd: vineyardd-sample
        scheduling.k8s.v6d.io/job: v6d-workflow-demo-job1
    spec:
      restartPolicy: Never
      containers:
      - name: job1
        image: ghcr.io/v6d-io/v6d/job1-with-scheduler
        env:
        - name: JOB_NAME
          value: v6d-workflow-demo-job1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/run
          name: vineyard-sock
        command: ["/bin/bash", "-c", "sleep infinity"]
      volumes:
      - name: vineyard-sock
        hostPath:
          path: /var/run/vineyard-kubernetes/vineyard-system/vineyardd-sample
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                     - v6d-workflow-demo-job1
              topologyKey: "kubernetes.io/hostname"
EOF
```
4. Run the following code in one pod and list the metadata in another pod.
```python
import time
import numpy as np
import vineyard

client = vineyard.connect('/var/run/vineyard.sock')

object = client.put(np.arange(10))
meta = vineyard.ObjectMeta()
meta['typename'] = 'vineyard::Sequence'
meta['size_'] = 1
meta.set_global(True)
meta.add_member('__elements_-0', object)
meta['__elements_-size'] = 1
tup = client.create_metadata(meta)
client.persist(tup)
```

```python
import vineyard
client = vineyard.connect('/var/run/vineyard.sock')
client.list_metadatas(pattern="*", limit=100)
```
